### PR TITLE
Covid19-Metric:Complete Project

### PR DESCRIPTION
**Pull request by Tumworobere**
**For this project, I achieved the following:**

- Chose an [API](https://corona-api.com/countries) for the project
-  Followed [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))
**Interactions:**
- Home page: When the page loads, the web app shows the Country's name and recovered cases and When the user clicks (or taps) on a category item, the application navigates to the details page.
- Details page: the web app retrieves data from the API to show detailed data in the category and When the user clicks on the "Back" button (<), the user navigates to the home page.
-  Created unit and integration tests.
- The project is a single-page application (SPA) built with React and Redux.
-  Every page (the main page and the pages for each item) have a unique route within the SPA.
-  The project is deployed and accessible online (Find the link in my README file).
-  Recorded a video for documentation

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @Tumworobere

Good job working on the project so far! 
✔️ No linter errors
✔️ App works as expected
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] When I click on the video link in your README file, I get a 404 error. Please fix it.
- [ ] According to the instructions as shown below, you need to choose just one colour for your website and be consistent with it. Please use just one colour on your website.
Screenshot 2022-02-05 at 13 19 54


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Tumworobere** [comment]
> ## STATUS: CHANGES REQUIRED ♻️♻️
> 
> Hello 👋🏽 @Tumworobere
> 
> Good job working on the project so far! ✔️ No linter errors ✔️ App works as expected However, there are some issues that you need to work on to go to the next project but you are almost there!
> ## Required Changes ♻️
> 
>     * [ ]  When I click on the video link in your README file, I get a 404 error. Please fix it.
> 
>     * [ ]  According to the instructions as shown below, you need to choose just one colour for your website and be consistent with it. Please use just one colour on your website.
> 
> 
> Screenshot 2022-02-05 at 13 19 54
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @Ghiftee .I have implemented the changes!

**Review by Emmyn5600 — APPROVED** [review]
STATUS: APPROVED :partying_face: 

Wooow👏, Your project is complete!  There is nothing else to say other than... it's time to merge it. 👏

Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Tumworobere** [comment]
> STATUS: APPROVED 🥳
> 
> Wooow👏, Your project is complete! There is nothing else to say other than... it's time to merge it. 👏
> 
> Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Thanks @Emmyn5600

**Pull request merged**
